# Generated by Django 3.2.4 on 2021-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, null=True)),
                ('last_name', models.CharField(max_length=75, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('ssn', models.CharField(max_length=25, null=True, unique=True)),
                ('driver_license_class', models.CharField(max_length=25, null=True)),
                ('driver_license_number', models.CharField(max_length=25, null=True)),
                ('state_issues', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('id_file', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('application_file', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('driver_license_file', models.FileField(blank=True, null=True, upload_to='driver_licenses/')),
                ('medical_card_file', models.FileField(blank=True, null=True, upload_to='medical_cards/')),
                ('birth_certificate_file', models.FileField(blank=True, null=True, upload_to='birth_certificates/')),
                ('drug_screening_file', models.FileField(blank=True, null=True, upload_to='drug_screenings/')),
                ('miscellaneous_file', models.FileField(blank=True, null=True, upload_to='miscellaneous/')),
            ],
        ),
    ]
