# Generated by Django 3.2.4 on 2021-07-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210701_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='state_issues',
            new_name='state_issued',
        ),
    ]
