# Generated by Django 3.2.4 on 2021-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_state_issues_student_state_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
